### PR TITLE
Renaming dashboard.ipynb -> datashader_dashboard and adding logo

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Comment by jbednar** [comment]
Can you please merge the changes from https://github.com/pyviz/datashader/pull/768, maybe waiting for hvplot to be released so that it works?

**Comment by jsignell** [comment]
Sure, but hvplot isn't released yet, so I don't think the time is right.

**Comment by jbednar** [comment]
Right. In the meantime, doesn't intake need to be pinned here to avoid the problems that the datashader PR addresses?

**Comment by jsignell** [comment]
I got rid of the ranges in the catalog. It doesn't make a big difference in my opinion.

**Comment by jbednar** [comment]
Ah, that works too. :-)

**Pull request merged**
