### PR TITLE
Add Particle Swarm Optimisation Dashboard

### PR DESCRIPTION
**Pull request by scottire**
A dashboard (using Panel, Holoviews with a Bokeh backend) to interact with Particle Swarm Optimisation.
Let me know if you have any feedback or changes needed. 
I hope you don't mind me submitting these dashboards. I'm loving playing with these tools, thanks so much for releasing them and all the work you do! 
🚀

### CODE REVIEW

**Comment by jbednar** [comment]
Cool! Thanks for the contributions, and keep 'em coming!

**Comment by scottire** [comment]
Great! 😄 

Is this deployed anywhere? I'm going to post about it on Twitter and my blog so would be nice to include a link to the dashboard.

**Comment by jlstevens** [comment]
Thanks for this contribution! 

I'm going to deploy it now and I'll ping you back when it is up. A website rebuild will be needed to make the link public and easily accessible.

**Comment by jlstevens** [comment]
The live dashboard is up! https://particle-swarm-optimisation.pyviz.demo.anaconda.com/pso

That said, I think `.servable` is mistakenly being called once before the final dashboard, resulting in this extra plot at the top of the page:

image

I'll go ahead and make some minor fixes and redeploy.

**Comment by scottire** [comment]
Great! Thanks for fixing that!

**Comment by jbednar** [comment]
Note that the deployment URL needs to change to match the name of the project now that that's been adjusted for our website conventions; it will end up at https://particle-swarms.pyviz.demo.anaconda.com/ instead of the above URL...

**Comment by jlstevens** [comment]
@jbednar Deployment updated. @scottire The dashboard URL will now be https://particle-swarms.pyviz.demo.anaconda.com/pso and is now unlikely to change.

**Comment by jbednar** [comment]
Despite that claim, it's now at https://particle-swarms.pyviz.demo.anaconda.com , and _that_ is unlikely to change.  (That URL worked before, but the "pso" one did not fit our conventions...)

**Comment by jlstevens** [comment]
Yes, sorry! It still wasn't quite right and the link Jim posted is really the one that should never change...

**Pull request merged**
