### PR TITLE
Add genetic algorithm

### PR DESCRIPTION
**Pull request by scottire**
A dashboard (using Panel, Holoview and Bokeh) to interact with Genetic Algorithm.
I've added some descriptions around the different parts of the algorithm, along with a small description of the different interactive elements.

Happy to take feedback or add changes where needed. I'm also a little bit unsure whether to include the `.servable()` call or `pn.serve`.

### CODE REVIEW

**Comment by philippjfr** [comment]
Nice! I'll try this out tomorrow and then hopefully we can get it merged and deployed asap.

**Comment by philippjfr** [comment]
One quick comment, would you mind clearing the notebook?

**Comment by scottire** [comment]
Great. Sure, that's done now.

**Comment by philippjfr** [comment]
Looks good to me.

**Comment by philippjfr** [comment]
Thanks! It's a really neat example.

**Pull request merged**
