### PR TITLE
Fixing up glaciers logo

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good. @philippjfr may prefer using the Panel logo instead?

**Comment by philippjfr** [comment]
I would, makes more sense to me.

**Comment by philippjfr** [comment]
Alternatively we drop it entirely. There's already the oggm logo there.

**Comment by jbednar** [comment]
I think having the Panel logo on there is good, as there is a Dash version (which we link to) that can have the Dash logo.

**Pull request merged**
