### PR TITLE
Only include user-facing fields in zipped version of anaconda-project

### PR DESCRIPTION
**Pull request by jsignell**
From talking with Rachel, it seems that the extra fields in the anaconda-project are confusing to people and hinder the legibility of the files. This PR deals with the anaconda-project.yml that ends up in the zip file. It strips out two different sets of fields:
 - fields that we use the build the site, but anaconda-project doesn't know about. 
 - commands and env specs used in testing that aren't user facing.

Original:
```yaml
# To reproduce: install 'anaconda-project', then 'anaconda-project run'
name: boids
description: Boids models of swarm intelligence using HoloViews
created: 2015-01-01
maintainers:
  - philippjfr
labels:
  - holoviews

channels: []

dependencies: &deps
  - python=3.6
  - notebook=5.7.8
  - ipykernel=5.1.0
  - nomkl
  - bokeh=1.2.0
  - holoviews=1.12.3
  - numpy=1.16.4

packages: *deps

commands:
  notebook:
    notebook: boids.ipynb
  test:
    unix:    pytest --nbsmoke-run -k *.ipynb --ignore envs
    windows: pytest --nbsmoke-run -k *.ipynb --ignore envs
    env_spec: test
  lint:
    unix:    pytest --nbsmoke-lint -k *.ipynb --ignore envs
    windows: pytest --nbsmoke-lint -k *.ipynb --ignore envs
    env_spec: test

variables: {}
downloads: {}

env_specs:
  default: {}
  test:
    packages:
      - nbsmoke=0.2.8
      - pytest=4.4.1
```
Version in zip file:
```yaml
name: boids
description: Boids models of swarm intelligence using HoloViews
channels: []
dependencies: &id001
- python=3.6
- notebook=5.7.8
- ipykernel=5.1.0
- nomkl
- bokeh=1.2.0
- holoviews=1.12.3
- numpy=1.16.4
packages: *id001
commands:
  notebook:
    notebook: boids.ipynb
variables: {}
downloads: {}
env_specs:
  default: {}
```

### CODE REVIEW

**Comment by jsignell** [comment]
Note that the only "unusual" thing that I am leaving in is the handling of dependcies/packages. That part will also go away once a newer anaconda-project makes its way into AE.

**Comment by jbednar** [comment]
Ok.  Is it necessary to have all the empty fields (channels, variables, downloads)?  We might maintain a skeleton somewhere that includes those, but I wouldn't think they should be in each YML if they are empty like that.  Is there a good reason that &deps changed to the less readable &id001?

**Comment by jsignell** [comment]
I can get rid of empty fields, but there is no way to maintain that `&deps` using pyyaml. It would be possible using ruamel.yaml, but I am hesitant to add that dependency since anaconda-project requires pyyaml. 

ref: https://stackoverflow.com/questions/37413345/yaml-anchors-definitions-loading-in-pyyaml

**Comment by jsignell** [comment]
```yaml
name: boids
description: Boids models of swarm intelligence using HoloViews
packages: &id001
- python=3.6
- notebook=5.7.8
- ipykernel=5.1.0
- nomkl
- bokeh=1.2.0
- holoviews=1.12.3
- numpy=1.16.4
dependencies: *id001
commands:
  notebook:
    notebook: boids.ipynb
env_specs:
  default: {}
```

**Comment by jbednar** [comment]
Ok, thanks.

**Pull request merged**
